import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createPluginServer } from '../src/plugin/server';
import { fixtureService } from './plugin-protocol-fixture';
import type { MatchView } from '../src/plugin/view';
import { POOL } from '../src/rules/setup';
const service = fixtureService();
const game = (value: any) => { const {boardId, ...state} = value; return state; };
const server = createPluginServer({ service, actorId: 'alice', resourceHtml: '<html>board</html>', publicOrigin: 'https://kingdown.example' });
const client = new Client({ name: 'protocol-check', version: '1' });
const [a, b] = InMemoryTransport.createLinkedPair();
await server.connect(a); await client.connect(b);
try {
  const tools = (await client.listTools()).tools;
  assert.equal(tools.length, 8);
  const boardResource = (tools.find(tool => tool.name === 'kingdown_open')!._meta?.ui as any).resourceUri;
  assert.match(boardResource, /^ui:\/\/kingdown\/board-[a-f0-9]{64}\.html$/);
  for (const tool of tools) { assert.equal(tool.annotations?.destructiveHint, false); assert.equal(tool.annotations?.openWorldHint, false); assert.equal((tool._meta?.ui as any).resourceUri, boardResource); }
  assert.deepEqual((tools.find(tool => tool.name === 'kingdown_move')!._meta?.ui as any).visibility, ['app']);
  const resource = await client.readResource({ uri: boardResource });
  assert.equal(resource.contents[0].mimeType, 'text/html;profile=mcp-app');
  const opened = await client.callTool({ name: 'kingdown_open', arguments: {} });
  const view = opened.structuredContent as unknown as MatchView;
  const army = view.snapshot.fen.split(' ')[0].split('/').at(-1)!;
  assert.equal([...army].filter(piece => piece === 'K').length, 1);
  const available = POOL.split('');
  for (const piece of army.replace('K', '')) { const index = available.indexOf(piece); assert(index >= 0, `${piece} is outside the current army pool`); available.splice(index, 1); }
  const command = { matchId: view.matchId, id: 'one', expectedRevision: 0, lan: 'e2-e4' };
  const moved = await client.callTool({ name: 'kingdown_move', arguments: command });
  assert.equal((moved.structuredContent as any).snapshot.revision, 1);
  const replay = await client.callTool({ name: 'kingdown_move', arguments: command });
  assert.deepEqual(replay.structuredContent, moved.structuredContent);
  const resumed = await client.callTool({ name: 'kingdown_open', arguments: {} });
  assert.deepEqual(game(resumed.structuredContent), moved.structuredContent);
  assert.notEqual(resumed.structuredContent!.boardId, view.boardId);
  const friend = await client.callTool({ name: 'kingdown_open', arguments: { mode: 'friend' } });
  const friendView = friend.structuredContent as unknown as MatchView;
  assert.notEqual(friendView.matchId, view.matchId); assert.equal(friendView.mode, 'friend'); assert.equal(friendView.waiting, true);
  assert.deepEqual(game((await client.callTool({ name: 'kingdown_open', arguments: {} })).structuredContent), game(friend.structuredContent));
  const solo = await client.callTool({ name: 'kingdown_open', arguments: { mode: 'solo' } });
  const soloView = solo.structuredContent as unknown as MatchView;
  assert.notEqual(soloView.matchId, view.matchId); assert.notEqual(soloView.matchId, friendView.matchId); assert.equal(soloView.mode, 'solo');
  assert.deepEqual(game((await client.callTool({ name: 'kingdown_open', arguments: { matchId: view.matchId, mode: 'friend' } })).structuredContent), moved.structuredContent);
  const selected = await client.callTool({name:'kingdown_create',arguments:{mode:'solo',boardId:view.boardId}});
  const reopened = await client.callTool({name:'kingdown_get',arguments:{matchId:view.matchId,boardId:view.boardId}});
  assert.equal(reopened.structuredContent!.matchId,selected.structuredContent!.matchId);
  assert.equal((await client.callTool({name:'kingdown_get',arguments:{matchId:view.matchId,boardId:resumed.structuredContent!.boardId}})).structuredContent!.matchId,view.matchId);
  assert.equal((await client.callTool({ name: 'kingdown_get', arguments: { matchId: view.matchId, actorId: 'mallory' } })).isError, true);
  assert.equal((await client.callTool({ name: 'kingdown_move', arguments: { ...command, id: 'two' } })).isError, true);
  service.get = async () => { throw new Error('database password=never-share'); };
  const failed = await client.callTool({ name: 'kingdown_get', arguments: { matchId: view.matchId } });
  assert.equal(failed.isError, true); assert(!JSON.stringify(failed).includes('never-share'));
  console.log('PASS: SDK tools/resource, app visibility, explicit new solo/friend games, latest/exact saved game, real engine move, duplicate command, stale revision, actor injection rejection, sanitized internal errors');
} finally { await client.close(); await server.close(); await service.close(); }
